use mysql;
-- QUESTION NO 1-------------------------------
create table DEPT (
DEPTNO INT(2),
DNAME VARCHAR(15),
LOC VARCHAR(10));
DESC DEPT;
INSERT INTO DEPT (DEPTNO,DNAME,LOC)VALUES
(10,'ACCOUNTING','NEW YORK'),
(20,'RESEARCH','DALLAS'),
(30,'SALES','CHICAGO'),
(40,'OPERATIONS','BOSTON');
select * FROM DEPT;

-- QUESTION NO 2-------------------------------
CREATE TABLE EMP (
EMPNO INT(4),
ENAME VARCHAR(10),
JOB VARCHAR(9),
HIREDATE DATE,
SAL float(7,2),
COMM float(7,2),
DEPTNO INT(2));
DESC EMP;
INSERT INTO EMP (EMPNO,ENAME,JOB,HIREDATE,SAL,COMM,DEPTNO)
VALUES 
(7839,'KING',' MANAGER', '1991-11-17', 5000, NULL, 10),
(7698 ,'BLAKE',' CLERK' ,'1981-05-01' ,2850 ,NULL ,30),
(7782, 'CLARK','MANAGER', '1981-06-09', 2450, NULL, 10),
(7566 ,'JONES','CLERK' ,'1981-04-02' ,2975, NULL ,20),
(7654,'MARTIN','SALESMAN', '1981-09-28', 1250, 1400, 30),
(7499 ,'ALLEN','SALESMAN','1981-02-20', 1600, 300, 30);
select * FROM EMP;

-- QUESTION 3------------------------------------
SELECT ENAME FROM EMP WHERE SAL>=2500 AND SAL<=5000;

-- QUESTION 4 -------------------------------
SELECT ENAME from EMP order by ENAME DESC;

-- QUESTION 5 ----------------------------
SELECT lower(JOB)FROM EMP;


-- QUESTION 6------------------------
SELECT ENAME ,length(ENAME) FROM EMP;

-- QUESTION 7------------------
SELECT DEPTNO,count(ENAME)from EMP group by DEPTNO;

-- QUESTION 8----------------------
SELECT DNAME , ENAME FROM DEPT ,emp
WHERE DEPT.DEPTNO=EMP.DEPTNO; 

-- QUESTION 9 ---------------------
SELECT instr(ENAME,'AR') FROM EMP;

-- QUESTION 10--------------------
SELECT EMPNO,ENAME,SAL*0.2 AS "HRA" from EMP; 

-- SECTION II - QUESTION 1-------------------------

CREATE TABLE TEMPP(
STRING1 VARCHAR (20),
STRING2 VARCHAR(20),
OUTPUT VARCHAR(20));

DELIMITER // 
CREATE PROCEDURE PROC1(A VARCHAR(20),B VARCHAR (20))
BEGIN
DECLARE X INT DEFAULT 0;
insert into tempp (STRING1,STRING2)values(a,b);
 if X < (SELECT instr(STRING2,a)from TEMPP WHERE STRING2=B ) THEN
	INSERT INTO TEMPP (OUTPUT) VALUES ('SUBTRING PRESENT');
     
    ELSE 
    INSERT INTO TEMPP (OUTPUT) VALUES ('SUBTRING NOT PRESENT');
    END IF;
END; //
DELIMITER ;
CALL PROC1('DAC','CDAC');
SELECT * FROM TEMPP;

-- SECTION II QUESTION NO 2-----------------------
DELIMITER //
create function FUNC1(X INT,Y INT,Z INT)
RETURNS BOOLEAN
deterministic
BEGIN 
	IF X<(Y+Z)THEN
		IF Y<(X+Z) THEN
			IF Z<(Z+Y)THEN
            RETURN TRUE;
            ELSE 
			RETURN FALSE;
            END IF;
        ELSE 
		RETURN FALSE;    
		END IF;
	ELSE 
    RETURN FALSE;
    END IF;
END; //
DELIMITER ;
 

-- CALLING PROBGRAMME--
DELIMITER //
CREATE PROCEDURE CALL1()
BEGIN 
declare X boolean;
SET X=FUNC1(3,4,5);
SELECT X FROM DUAL;
END; //
DELIMITER ;
CALL CALL1();
 


    